version: "3.9"

services:
  db:
    container_name: crypto-db
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5420:5432