docker-compose up -d
source bin/activate
pip install -r requirements.txt
source .creds/setall.sh
STATIC_ROOT=$STATIC_ROOT CBA_API_KEY=$CBA_API_KEY CBA_API_SECRET=$CBA_API_SECRET CRYPTO_DB=$CRYPTO_DB CRYPTO_DB_USER=$CRYPTO_DB_USER CRYPTO_DB_PASS=$CRYPTO_DB_PASS CRYPTO_DB_HOST=$CRYPTO_DB_HOST CRYPTO_DB_PORT=$CRYPTO_DB_PORT python manage.py makemigrations
STATIC_ROOT=$STATIC_ROOT CBA_API_KEY=$CBA_API_KEY CBA_API_SECRET=$CBA_API_SECRET CRYPTO_DB=$CRYPTO_DB CRYPTO_DB_USER=$CRYPTO_DB_USER CRYPTO_DB_PASS=$CRYPTO_DB_PASS CRYPTO_DB_HOST=$CRYPTO_DB_HOST CRYPTO_DB_PORT=$CRYPTO_DB_PORT python manage.py migrate
STATIC_ROOT=$STATIC_ROOT CBA_API_KEY=$CBA_API_KEY CBA_API_SECRET=$CBA_API_SECRET CRYPTO_DB=$CRYPTO_DB CRYPTO_DB_USER=$CRYPTO_DB_USER CRYPTO_DB_PASS=$CRYPTO_DB_PASS CRYPTO_DB_HOST=$CRYPTO_DB_HOST CRYPTO_DB_PORT=$CRYPTO_DB_PORT python manage.py collectstatic --no-input
STATIC_ROOT=$STATIC_ROOT CBA_API_KEY=$CBA_API_KEY CBA_API_SECRET=$CBA_API_SECRET CRYPTO_DB=$CRYPTO_DB CRYPTO_DB_USER=$CRYPTO_DB_USER CRYPTO_DB_PASS=$CRYPTO_DB_PASS CRYPTO_DB_HOST=$CRYPTO_DB_HOST CRYPTO_DB_PORT=$CRYPTO_DB_PORT python manage.py runserver 0.0.0.0:8000
unset STATIC_ROOT CBA_API_KEY CBA_API_SECRET CRYPTO_DB CRYPTO_DB_USER CRYPTO_DB_PASS CRYPTO_DB_HOST CRYPTO_DB_PORT